# Copyright (C) 2025 Gen Astro LLC
# SPDX-License-Identifier: LicenseRef-GenAstro-SourceAvailable-1.0

# A constant in the dynamics, identified from a trajectory.
#
# Truth: **analytic**. The data is `exp(-0.1 t)` sampled exactly, and `ẋ = -p x` with `x(0) = 1`
# reproduces it exactly when `p = 0.1`. So the optimum is a parameter of 0.1, a final state of
# `exp(-0.1)`, and a cost of zero — a fit with no residual, which makes every figure here exact
# rather than a tolerance someone chose.
#
#   estimate   p
#   subject to ẋ = -p x,  x(0) = 1,  fitted to exp(-0.1 t) over [0, 1]
#
# What this covers that the other collocation cases do not:
#
#   · a **parameter** as a solver variable — `Vary(parameter, phase)`, `@partial(f, parameter)`
#     and the parameter columns of the defect Jacobian, which nothing else in the open suite
#     reaches;
#   · a **control-free phase**, where nothing is steering and the parameter is the whole answer;
#   · an objective with **no declared partial at all**, so the cost gradient comes entirely from
#     automatic differentiation.
#
# The problem is the regression suite's uc15, recorded at 0.1 under LGL. This file transcribes it
# with Hermite-Simpson.

using SNOW
using LinearAlgebra
using EpicycleBase
using AstroSolve
using Test

struct _PidState{T} <: AbstractState; x::T end

const _PID_TRUE_P = 0.1

# Control-free: the fourth argument is unused because nothing steers this phase.
_pid_dynamics!(dy, y::_PidState, u, p, t, model) = (dy[1] = -p[1] * y.x)

@partial(_pid_dynamics!, state) do dF, y, u, p, t, model
    dF[1, 1] = -p[1]
end

@partial(_pid_dynamics!, parameter) do dF, y, u, p, t, model
    dF[1, 1] = -y.x
end

_pid_initial(c) = [state(c).x]
@partial(_pid_initial, state) do c
    [1.0]
end

# Left to AD on purpose. The integrand depends on `t` as well as on the state, and a hand-written
# partial buys nothing here; what it exercises is the cost gradient falling back entirely to
# automatic differentiation, which no other collocation case in this suite does.
_pid_fit_error(c) = (state(c).x - exp(-_PID_TRUE_P * c.t))^2

"""Build the identification phase, started from a parameter guess of `p_guess`."""
function _pid_phase(; n_steps = 20, p_guess = 0.5)
    phase = CollocationPhase(
        name          = :param_id,
        transcription = HermiteSimpson(n_steps = n_steps),
        dynamics      = _pid_dynamics!,
        state         = _PidState,
        tspan         = (0.0, 1.0))

    Vary(state,     phase; guess = [1.0 exp(-_PID_TRUE_P)],
                           lower_bound = [-10.0], upper_bound = [10.0])
    Vary(parameter, phase; guess = [p_guess],
                           lower_bound = [0.0], upper_bound = [2.0])

    Constraint(_pid_initial, phase; equals = [1.0], at = Initial())

    Objective(_pid_fit_error, phase; sense = Min(), at = Path())
    return phase
end

@testset "parameter identification — the data really is generated by p = 0.1" begin
    # The truth claim before it is used as truth: the decay the data was drawn from is the exact
    # solution of the dynamics at p = 0.1, so a perfect fit has zero residual and there is no
    # tolerance to argue about downstream.
    sol(t, p) = exp(-p * t)
    h = 1e-7
    for t in (0.0, 0.25, 0.5, 0.75, 1.0)
        dx = (sol(t + h, _PID_TRUE_P) - sol(t - h, _PID_TRUE_P)) / (2h)
        @test dx ≈ -_PID_TRUE_P * sol(t, _PID_TRUE_P) atol = 1e-8
    end
    @test sol(0.0, _PID_TRUE_P) ≈ 1.0 atol = 1e-14
    @test sol(1.0, _PID_TRUE_P) ≈ 0.904837 atol = 1e-6
end

@testset "parameter identification — the parameter is recovered from the trajectory" begin
    phase = _pid_phase()
    result = solve!(Sequence(phase))

    @test result.info === :Solve_Succeeded

    # The parameter is the answer here, not a by-product of it.
    p_hat = get_param_value(phase)
    @test length(p_hat) == 1
    @test p_hat[1] ≈ _PID_TRUE_P atol = 1e-5

    # A residual-free fit, which is what makes the recovery exact rather than merely close.
    @test result.objective ≈ 0.0 atol = 1e-9
    @test result.objective >= -1e-12          # a squared cost cannot go negative

    # And the trajectory the identified parameter produces.
    @test get_final_state(phase).x ≈ exp(-_PID_TRUE_P) atol = 1e-5
    @test get_initial_state(phase).x ≈ 1.0 atol = 1e-8
end

@testset "parameter identification — the whole decay is matched, not just its end" begin
    # The cost is an integral over the arc, so a fit that is right at the endpoints and wrong
    # between them would still score well if the quadrature were wrong. Checking every node
    # against the closed form separates those.
    phase = _pid_phase()
    solve!(Sequence(phase))

    ts = get_node_times(phase)
    xs = phase._Y
    @test length(ts) == size(xs, 2)
    for k in eachindex(ts)
        @test xs[1, k] ≈ exp(-_PID_TRUE_P * ts[k]) atol = 1e-5
    end

    # The state is a decay: positive and strictly decreasing across the arc.
    @test all(xs[1, :] .> 0)
    @test issorted(xs[1, :]; rev = true)
end

@testset "parameter identification — the answer does not depend on the starting guess" begin
    # A parameter estimate that moved with its guess would mean the parameter columns of the
    # Jacobian were not reaching the solver: it would stop wherever it started and report success.
    # Three guesses spanning the bound, one answer.
    answers = Float64[]
    for g in (0.02, 0.5, 1.5)
        phase = _pid_phase(p_guess = g)
        r = solve!(Sequence(phase))
        @test r.info === :Solve_Succeeded
        push!(answers, get_param_value(phase)[1])
    end

    for a in answers
        @test a ≈ _PID_TRUE_P atol = 1e-4
    end
    @test maximum(answers) - minimum(answers) < 1e-4
end
