# Copyright (C) 2025 Gen Astro LLC
# SPDX-License-Identifier: LicenseRef-GenAstro-SourceAvailable-1.0

# UDU covariance factorization — analytic truth.
#
# Every property here is an identity, so the expected answer is not generated by the code
# under test: P == U·diag(D)·Uᵀ, the Thornton update equals Φ P Φᵀ + G Q Gᵀ formed directly,
# and the Bierman update equals the Joseph-form Kalman update. That is analytic truth, and it
# needs no truth data and no solver.
#
# UDU.jl was 0 of 89 coverable lines.

using AstroSolve
using LinearAlgebra
using Random
using Test

const _UDU = AstroSolve.UDU

"""A random symmetric positive-definite matrix with a controlled condition number."""
function _spd(n::Int; rng = MersenneTwister(42), scale = 1.0)
    A = randn(rng, n, n)
    return Symmetric(A * A' + scale * n * I) |> Matrix
end

@testset "UDU — factorization round trips" begin
    for n in 1:8
        P = _spd(n)
        U, D = _UDU.udu_from_P(P)

        @test size(U) == (n, n)
        @test length(D) == n

        # U is unit upper triangular: ones on the diagonal, zeros below.
        @test all(diag(U) .≈ 1.0)
        @test all(abs.(tril(U, -1)) .< 1e-14)

        # D is positive, which is what makes the factorization meaningful for a covariance.
        @test all(D .> 0)

        # The identity the whole construction exists for.
        @test _UDU.udu_to_P(U, D) ≈ P atol = 1e-10
    end

    # A diagonal covariance factors to the identity and its own diagonal, exactly.
    P = Diagonal([2.0, 5.0, 0.5]) |> Matrix
    U, D = _UDU.udu_from_P(P)
    @test U ≈ Matrix(I, 3, 3) atol = 1e-14
    @test D ≈ [2.0, 5.0, 0.5] atol = 1e-14

    # P is not modified.
    P0 = _spd(4)
    P_copy = copy(P0)
    _UDU.udu_from_P(P0)
    @test P0 == P_copy
end

@testset "UDU — Thornton time update against the direct form" begin
    # Truth: form Φ P Φᵀ + G diag(Q) Gᵀ directly and compare. The factored update must agree,
    # which is the only thing that makes it a substitute for the direct computation.
    rng = MersenneTwister(7)
    for n in 2:6
        P = _spd(n; rng = rng)
        Φ = I(n) + 0.1 .* randn(rng, n, n)

        # Deterministic dynamics first: no process noise at all.
        U, D = _UDU.udu_from_P(P)
        _UDU.thornton_time_update!(U, D, Φ, zeros(n, 0), Float64[])
        @test _UDU.udu_to_P(U, D) ≈ Φ * P * Φ' atol = 1e-8

        # Then with process noise on every state.
        nq = n
        G  = Matrix{Float64}(I, n, nq)
        Q  = fill(0.05, nq)
        U2, D2 = _UDU.udu_from_P(P)
        _UDU.thornton_time_update!(U2, D2, Φ, G, Q)
        @test _UDU.udu_to_P(U2, D2) ≈ Φ * P * Φ' + G * Diagonal(Q) * G' atol = 1e-8

        # And with process noise on a subset, which is the shape a real model has.
        nq = 1
        G  = reshape(Float64[i == n ? 1.0 : 0.0 for i in 1:n], n, nq)
        Q  = [0.3]
        U3, D3 = _UDU.udu_from_P(P)
        _UDU.thornton_time_update!(U3, D3, Φ, G, Q)
        @test _UDU.udu_to_P(U3, D3) ≈ Φ * P * Φ' + G * Diagonal(Q) * G' atol = 1e-8

        # The result stays positive definite, which is the property the factored form buys.
        @test all(D3 .> 0)
        @test isposdef(Symmetric(_UDU.udu_to_P(U3, D3)))
    end

    # The identity transition with no noise must change nothing.
    P = _spd(3)
    U, D = _UDU.udu_from_P(P)
    _UDU.thornton_time_update!(U, D, Matrix{Float64}(I, 3, 3), zeros(3, 0), Float64[])
    @test _UDU.udu_to_P(U, D) ≈ P atol = 1e-9
end

@testset "UDU — Bierman update against the Kalman form" begin
    # Truth: the textbook scalar Kalman update, formed directly.
    #   K = P h / (hᵀ P h + R),  x⁺ = x + K ν,  P⁺ = (I − K hᵀ) P (I − K hᵀ)ᵀ + K R Kᵀ
    # The Joseph form is used for P⁺ because it is the numerically honest one to compare
    # against, and it is what the factored update is meant to reproduce without forming P.
    rng = MersenneTwister(11)
    for n in 2:6
        P = _spd(n; rng = rng)
        x = randn(rng, n)
        h = randn(rng, n)
        R = 0.4
        ν = 0.75

        K_ref  = P * h / (dot(h, P * h) + R)
        x_ref  = x + K_ref * ν
        A      = I(n) - K_ref * h'
        P_ref  = A * P * A' + K_ref * R * K_ref'

        U, D = _UDU.udu_from_P(P)
        x_w  = copy(x)
        K    = _UDU.bierman_measurement_update!(U, D, x_w, h, R, ν)

        @test K   ≈ K_ref atol = 1e-9
        @test x_w ≈ x_ref atol = 1e-9
        @test _UDU.udu_to_P(U, D) ≈ P_ref atol = 1e-8

        # An update never increases uncertainty along the measured direction.
        @test dot(h, _UDU.udu_to_P(U, D) * h) <= dot(h, P * h) + 1e-9
        @test all(D .> 0)
    end

    # A measurement with no information content — infinite variance in the limit — moves the
    # state hardly at all, while a very precise one moves it onto the observation.
    P = Diagonal([1.0, 1.0]) |> Matrix
    U, D = _UDU.udu_from_P(P)
    x = [0.0, 0.0]
    _UDU.bierman_measurement_update!(U, D, x, [1.0, 0.0], 1e8, 5.0)
    @test abs(x[1]) < 1e-6

    U2, D2 = _UDU.udu_from_P(P)
    x2 = [0.0, 0.0]
    _UDU.bierman_measurement_update!(U2, D2, x2, [1.0, 0.0], 1e-8, 5.0)
    @test x2[1] ≈ 5.0 atol = 1e-6
    @test x2[2] ≈ 0.0 atol = 1e-12          # an unobserved state is untouched
end

@testset "UDU — sequential scalar updates equal a batch update" begin
    # Applying two uncorrelated measurements one at a time must equal the batch update with a
    # diagonal R. This is the property that justifies processing a vector observation scalar
    # by scalar, which is how the estimators use this module.
    n = 4
    P = _spd(n; rng = MersenneTwister(3))
    x = zeros(n)
    H = [1.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0]
    R = Diagonal([0.2, 0.5])
    z = [1.5, -0.8]

    K_b   = P * H' / (H * P * H' + R)
    x_ref = x + K_b * (z - H * x)
    A     = I(n) - K_b * H
    P_ref = A * P * A' + K_b * R * K_b'

    U, D = _UDU.udu_from_P(P)
    x_w  = copy(x)
    for i in 1:2
        h = H[i, :]
        _UDU.bierman_measurement_update!(U, D, x_w, h, R[i, i], z[i] - dot(h, x_w))
    end

    @test x_w ≈ x_ref atol = 1e-8
    @test _UDU.udu_to_P(U, D) ≈ P_ref atol = 1e-8
end

@testset "UDU — input validation" begin
    # The exception type and its message are both asserted: a test that
    # only checks the type passes on "invalid input" and tells the caller nothing.
    P = _spd(3)
    U, D = _UDU.udu_from_P(P)

    # A matrix that is symmetric but indefinite is not a covariance.
    @test_throws DomainError _UDU.udu_from_P([1.0 2.0; 2.0 1.0])
    msg = try; _UDU.udu_from_P([1.0 2.0; 2.0 1.0]); catch e; sprint(showerror, e); end
    @test occursin("positive definite", msg)
    @test occursin("pivot", msg)

    # Shapes that disagree with D are caught before any arithmetic runs.
    @test_throws ArgumentError _UDU.thornton_time_update!(U, D, zeros(2, 2), zeros(3, 0), Float64[])
    @test_throws ArgumentError _UDU.thornton_time_update!(U, D, Matrix{Float64}(I, 3, 3),
                                                          zeros(3, 2), [0.1])
    shape_msg = try
        _UDU.thornton_time_update!(U, D, zeros(2, 2), zeros(3, 0), Float64[])
    catch e
        sprint(showerror, e)
    end
    @test occursin("(3, 3)", shape_msg)        # what was expected
    @test occursin("(2, 2)", shape_msg)        # and what arrived

    @test_throws ArgumentError _UDU.bierman_measurement_update!(U, D, zeros(2), [1.0,0,0], 1.0, 0.0)
    @test_throws ArgumentError _UDU.bierman_measurement_update!(U, D, zeros(3), [1.0,0], 1.0, 0.0)
    @test_throws DomainError   _UDU.bierman_measurement_update!(U, D, zeros(3), [1.0,0,0], 0.0, 0.0)
    @test_throws DomainError   _UDU.bierman_measurement_update!(U, D, zeros(3), [1.0,0,0], -1.0, 0.0)

    r_msg = try
        _UDU.bierman_measurement_update!(U, D, zeros(3), [1.0,0,0], -1.0, 0.0)
    catch e
        sprint(showerror, e)
    end
    @test occursin("positive", r_msg)
end
