# Copyright (C) 2026 Gen Astro LLC
# SPDX-License-Identifier: LicenseRef-GenAstro-SourceAvailable-1.0

# The words a script is written in: solve! for estimation, Link between collocation phases,
# check_partials, and a ForceModel as a phase's dynamics.
#
# Truth, by section:
#   solve!(problem, data)     the lower-level estimator on the same records, which solve! must
#                             reproduce exactly, and noise-free range and Doppler generated by
#                             propagating a known state, which every method and the file form
#                             must recover.
#   Link                      analytic. A brachistochrone split into two linked phases is still the
#                             cycloid, so the joined descent time must match the closed form and
#                             the one-phase solve.
#   check_partials            by construction: a correct partial agrees with finite differences
#                             and a deliberately wrong one is reported.
#   forcemodel_rhs            AstroProp's own force sum, which `propagate!` uses.
#
# Self-contained: the helpers are prefixed `_sv` so the file can run in the same process as the
# files that define similar ones.

using Test
using LinearAlgebra
using Logging

using EpicycleBase
using AstroEpochs
using AstroStates
using AstroFrames
using AstroUniverse
using AstroModels
using AstroProp
using AstroSolve
using AstroSolve: initialize!, set_dynamics!
using AstroProp: Vern9

const _SV_BLS = AstroSolve.BatchLeastSquares

# ─────────────────────────────────────────────────────────────────────────────
# Method structs
# ─────────────────────────────────────────────────────────────────────────────

@testset "Optimize, Batch and Sequential — defaults and the solver options they make" begin
    o = Optimize()
    @test (o.max_iter, o.tol, o.print_level, o.derivatives, o.record_iterations) ==
          (500, 1e-6, 5, :user, false)
    @test isempty(o.extra)
    @test Optimize(extra = Dict("sb" => "yes")).extra == Dict{String,Any}("sb" => "yes")

    b = Batch()
    @test (b.n_iters, b.tol, b.verbose) == (15, 1e-9, false)

    s = Sequential()
    @test (s.iterations, s.tol, s.step_size, s.smoother) == (5, 1e-6, 1.0, nothing)
    @test Sequential(smoother = RTS()).smoother isa RTS

    # :fd picks forward finite differences, anything else the user's derivatives, and `extra`
    # overrides the defaults it collides with.
    fd   = AstroSolve._snow(Optimize(derivatives = :fd, extra = Dict("tol" => 1e-3)))
    user = AstroSolve._snow(Optimize())
    @test fd.derivatives isa AstroSolve.SNOW.ForwardFD
    @test user.derivatives isa AstroSolve.SNOW.UserDeriv
    @test fd.solver.options["tol"] == 1e-3

    # Two solves in one session must not share an IPOPT log, which IPOPT keeps open.
    @test AstroSolve._ipopt_log() != AstroSolve._ipopt_log()
end

# ─────────────────────────────────────────────────────────────────────────────
# solve!(problem, data) — estimation
# ─────────────────────────────────────────────────────────────────────────────

const _SV_T0    = Time("2020-03-01T00:00:00.000", TT(), ISOT())
const _SV_TRUTH = [6878.137, 0.0, 0.0, 0.0, 4.71754, 5.99820]
const _SV_SIG_R = 1e-3
const _SV_SIG_D = 1e-6

_sv_station() = GroundStation(name = "DSS-14", body = earth, latitude = 35.4267,
                              longitude = -116.89, altitude = 1.0, min_elevation = 0.0)
_sv_prop() = OrbitPropagator(ForceModel(PointMassGravity(earth, ())),
                             IntegratorConfig(Vern9(); dt = 60.0, reltol = 1e-12, abstol = 1e-12))
_sv_sc(y0) = Spacecraft(state = CartesianState(copy(y0)), time = _SV_T0,
                        coord_sys = CoordinateSystem(earth, ICRF()), name = "Sat")
_sv_specs(gs, sc) = AbstractMeasurement[
    TwoWayRange(  SignalPath(gs, sc, gs); noise = MeasurementNoise(_SV_SIG_R)),
    TwoWayDoppler(SignalPath(gs, sc, gs); noise = MeasurementNoise(_SV_SIG_D))]

"""Noise-free range and Doppler, read where a propagation of the truth stops."""
function _sv_records(offsets)
    gs, sc, prop = _sv_station(), _sv_sc(_SV_TRUTH), _sv_prop()
    recs = AstroSolve.ObservationRecord[]
    prev = 0.0
    for dt in offsets
        propagate!(prop, sc, StopAt(sc, PropDurationSeconds(), dt - prev))
        prev = dt
        t    = AstroEpochs._time_jd(sc.time.jd1, sc.time.jd2, sc.time.scale, :isot)
        y    = to_posvel(sc)
        path = SignalPath(gs, sc, gs)
        for (kind, spec) in ((:RANGE,   TwoWayRange(path;   noise = MeasurementNoise(_SV_SIG_R))),
                             (:DOPPLER, TwoWayDoppler(path; noise = MeasurementNoise(_SV_SIG_D))))
            push!(recs, AstroSolve.ObservationRecord(kind, t,
                                                     _SV_BLS._predict(spec, y, sc.time, sc),
                                                     "DSS-14"))
        end
    end
    return recs
end

const _SV_GUESS_ERR = [1.0, -1.0, 0.5, 1e-3, -1e-3, 5e-4]

function _sv_problem(; solve_for = true)
    gs    = _sv_station()
    guess = _SV_TRUTH .+ _SV_GUESS_ERR
    sc    = _sv_sc(guess)
    x0    = Vary(state, sc; guess = guess, covariance = Diagonal([1e2, 1e2, 1e2, 1e-2, 1e-2, 1e-2]))
    return ODProblem(spacecraft = sc, propagator = _sv_prop(), measurements = _sv_specs(gs, sc),
                     solve_for = solve_for ? [x0] : Any[]), x0
end

@testset "solve! for estimation — each method, from records and from a file" begin
    recs = _sv_records(60.0:60.0:5400.0)

    # Batch through solve! is the batch estimator, not an approximation of it.
    problem, x0 = _sv_problem()
    direct = _SV_BLS.solve_batch_ls!([x0], copy(recs); model = problem, n_iters = 15, tol = 1e-9)
    problem, _ = _sv_problem()
    batch = solve!(problem, copy(recs); method = Batch())
    @test batch.X_hat ≈ direct.X_hat rtol = 1e-12
    @test batch.P_hat ≈ direct.P_hat rtol = 1e-9
    @test norm(batch.X_hat[1:3] .- _SV_TRUTH[1:3]) < 5e-2

    # The same data written as a CCSDS TDM and handed over as the file.
    file = TrackingDataFile(tempname() * ".tdm")
    write_records(file, recs, TDMHeader("2020-03-01T12:00:00", "GEN ASTRO"),
                  [TDMSegmentMeta(time_system = "TT", participant_1 = "DSS-14",
                                  participant_2 = "Sat")])
    # The file keeps epochs to the millisecond, so the data differ from the records in the last
    # bits and the fit lands on the truth rather than on the in-memory answer.
    problem, _ = _sv_problem()
    from_file = solve!(problem, file; method = Batch())
    @test length(first(read_records(file))) == length(recs)
    @test norm(from_file.X_hat[1:3] .- _SV_TRUTH[1:3]) < 5e-2
    @test norm(from_file.X_hat[4:6] .- _SV_TRUTH[4:6]) < 5e-5
    rm(file.path; force = true)

    # Sequential: the filter alone, and the filter with its smoother.
    # The filter's estimate is at the last observation, so compare it with the truth flown there.
    truth_end = _sv_sc(_SV_TRUTH)
    propagate!(_sv_prop(), truth_end, StopAt(truth_end, PropDurationSeconds(), 5400.0))
    problem, _ = _sv_problem()
    filtered = solve!(problem, copy(recs); method = Sequential())
    @test filtered isa AstroSolve.ExtendedKalmanFilter.EKFResult
    @test norm(filtered.X_hat[1:3] .- to_posvel(truth_end)[1:3]) < 1.0

    problem, _ = _sv_problem()
    smoothed = solve!(problem, copy(recs); method = Sequential(iterations = 3, smoother = RTS()))
    @test !(smoothed isa AstroSolve.ExtendedKalmanFilter.EKFResult)
    @test norm(to_posvel(problem.spacecraft)[1:3] .- _SV_TRUTH[1:3]) < 1.0

    # A problem with nothing to estimate, and a method that is not an estimation method.
    empty_problem, _ = _sv_problem(solve_for = false)
    @test_throws ArgumentError solve!(empty_problem, recs; method = Batch())
    problem, _ = _sv_problem()
    @test_throws ArgumentError solve!(problem, recs; method = Optimize())
end

# ─────────────────────────────────────────────────────────────────────────────
# Collocation: a brachistochrone, one phase and two linked phases
# ─────────────────────────────────────────────────────────────────────────────

struct _SvState{T}   <: AbstractState;   x::T; y::T; v::T end
struct _SvControl{T} <: AbstractControl; θ::T             end
struct _SvModel;     g::Float64                           end
struct _SvPlanar{T}  <: AbstractState;   x::T; y::T      end
const _SV_G = 9.80665

function _sv_dynamics!(dy, y::_SvState, u::_SvControl, p, t, model)
    dy[1] = y.v * sin(u.θ)
    dy[2] = y.v * cos(u.θ)
    dy[3] = model.g * cos(u.θ)
end
@partial(_sv_dynamics!, state) do dF, y, u, p, t, model
    dF[1, 3] = sin(u.θ)
    dF[2, 3] = cos(u.θ)
end
@partial(_sv_dynamics!, control) do dF, y, u, p, t, model
    dF[1, 1] =  y.v * cos(u.θ)
    dF[2, 1] = -y.v * sin(u.θ)
    dF[3, 1] = -model.g * sin(u.θ)
end

_sv_start(c) = [state(c).x, state(c).y, state(c).v]
@partial(_sv_start, state) do c
    Matrix(1.0I, 3, 3)
end
_sv_target(c) = [state(c).x, state(c).y]
@partial(_sv_target, state) do c
    [1.0 0.0 0.0; 0.0 1.0 0.0]
end
_sv_duration(c) = final_time(c)
@partial(_sv_duration, final_time) do c
    [1.0]
end

function _sv_phase(name, tspan, xy0, xy1; n_steps = 10)
    p = CollocationPhase(name = name, transcription = HermiteSimpson(n_steps = n_steps),
                         dynamics = _sv_dynamics!, model = _SvModel(_SV_G),
                         state = _SvState, control = _SvControl, tspan = tspan)
    v0, v1 = sqrt(2_SV_G * xy0[2]), sqrt(2_SV_G * xy1[2])
    Vary(state, p; guess = [xy0[1] xy1[1]; xy0[2] xy1[2]; v0 v1],
         lower_bound = [-Inf, -Inf, 0.0], upper_bound = [Inf, Inf, Inf])
    Vary(control, p; guess = reshape([0.5, 1.0], 1, 2), lower_bound = [-π/2], upper_bound = [π/2])
    return p
end

@testset "Link — a brachistochrone in two linked phases is still the cycloid" begin
    quiet = Optimize(print_level = 0)

    one = _sv_phase(:whole, (0.0, 1.0), (0.0, 0.0), (2.0, 2.0); n_steps = 20)
    Vary(final_time, one; lower_bound = 0.1, upper_bound = 10.0)
    Constraint(_sv_start,  one; equals = [0.0, 0.0, 0.0], at = Initial())
    Constraint(_sv_target, one; equals = [2.0, 2.0],      at = Final())
    Objective(_sv_duration, one; sense = Min())
    @test solve!(Sequence(one); method = quiet).info === :Solve_Succeeded
    tf_one = get_final_time(one)
    @test tf_one ≈ 0.824479 atol = 1e-5

    first_half  = _sv_phase(:first,  (0.0, 0.5), (0.0, 0.0), (0.8, 1.0))
    second_half = _sv_phase(:second, (0.5, 1.0), (0.8, 1.0), (2.0, 2.0))
    Vary(final_time,   first_half;  lower_bound = 0.05, upper_bound = 5.0)
    Vary(initial_time, second_half; lower_bound = 0.05, upper_bound = 5.0)
    Vary(final_time,   second_half; lower_bound = 0.1,  upper_bound = 10.0)
    Constraint(_sv_start,  first_half;  equals = [0.0, 0.0, 0.0], at = Initial())
    Constraint(_sv_target, second_half; equals = [2.0, 2.0],      at = Final())
    Objective(_sv_duration, second_half; sense = Min())

    # Continuity of the state and of time where the phases meet.
    joined = Link(first_half, second_half; name = :halfway)
    # A collocation context hands back the phase's own state struct, so the residual is written
    # per field rather than as a vector difference.
    Constraint(joined; equals = zeros(4)) do c1, c2
        a, b = final_state(c1), initial_state(c2)
        [a.x - b.x, a.y - b.y, a.v - b.v, final_time(c1) - initial_time(c2)]
    end
    @test_throws ArgumentError Constraint((c1, c2) -> [0.0], joined; equals = [0.0], at = Final())

    seq = Sequence()
    add_sequence!(seq, first_half)
    add_sequence!(seq, second_half)
    @test solve!(seq; method = quiet).info === :Solve_Succeeded
    @test isempty(AstroSolve._PENDING)          # the link was registered and drained

    @test get_final_time(second_half) ≈ tf_one atol = 1e-3
    a, b = get_final_state(first_half), get_initial_state(second_half)
    @test [a.x, a.y, a.v] ≈ [b.x, b.y, b.v] atol = 1e-6
    @test get_final_time(first_half) ≈ get_initial_time(second_half) atol = 1e-6
end

"""The two halves of the brachistochrone, with every condition but the join."""
function _sv_halves()
    first_half  = _sv_phase(:first,  (0.0, 0.5), (0.0, 0.0), (0.8, 1.0))
    second_half = _sv_phase(:second, (0.5, 1.0), (0.8, 1.0), (2.0, 2.0))
    Vary(final_time,   first_half;  lower_bound = 0.05, upper_bound = 5.0)
    Vary(initial_time, second_half; lower_bound = 0.05, upper_bound = 5.0)
    Vary(final_time,   second_half; lower_bound = 0.1,  upper_bound = 10.0)
    Constraint(_sv_start,  first_half;  equals = [0.0, 0.0, 0.0], at = Initial())
    Constraint(_sv_target, second_half; equals = [2.0, 2.0],      at = Final())
    Objective(_sv_duration, second_half; sense = Min())
    return first_half, second_half
end

@testset "Link — continuity joins state and time in one line" begin
    first_half, second_half = _sv_halves()
    Constraint(continuity, Link(first_half, second_half))

    seq = Sequence()
    add_sequence!(seq, first_half)
    add_sequence!(seq, second_half)
    @test solve!(seq; method = Optimize(print_level = 0)).info === :Solve_Succeeded

    # The same cycloid as the one-phase solve, and the phases meet in state and time.
    @test get_final_time(second_half) ≈ 0.824479 atol = 1e-3
    a, b = get_final_state(first_half), get_initial_state(second_half)
    @test [a.x, a.y, a.v] ≈ [b.x, b.y, b.v] atol = 1e-6
    @test get_final_time(first_half) ≈ get_initial_time(second_half) atol = 1e-6

    # The residual itself: zero where the phases meet, the difference where they do not.
    c1 = AstroSolve.BoundaryContext(nothing, _SvState(1.0, 2.0, 3.0), 0.0, 0.5, Float64[])
    c2 = AstroSolve.BoundaryContext(_SvState(1.0, 2.5, 3.0), nothing, 0.6, 1.0, Float64[])
    @test continuity(c1, c2) ≈ [0.0, -0.5, 0.0, -0.1] atol = 1e-15

    # Only between two collocation phases, and only when their states are the same length.
    @test_throws ArgumentError Constraint(continuity, Link(first_half, second_half, first_half))
    planar = CollocationPhase(name = :planar, transcription = HermiteSimpson(n_steps = 4),
                              dynamics = _sv_dynamics!, model = _SvModel(_SV_G),
                              state = _SvPlanar, control = _SvControl, tspan = (0.0, 1.0))
    @test_throws ArgumentError AstroSolve._continuity_size(first_half, planar)
end

# ─────────────────────────────────────────────────────────────────────────────
# check_partials
# ─────────────────────────────────────────────────────────────────────────────

_sv_wrong_target(c) = [state(c).x, state(c).y]
@partial(_sv_wrong_target, state) do c
    [2.0 0.0 0.0; 0.0 1.0 0.0]                  # ∂x/∂x is 1, not 2
end

@testset "check_partials — agrees on correct partials and reports a wrong one" begin
    good = _sv_phase(:good, (0.0, 1.0), (0.0, 0.0), (2.0, 2.0))
    Vary(final_time, good; lower_bound = 0.1, upper_bound = 10.0)
    Constraint(_sv_start,  good; equals = [0.0, 0.0, 0.0], at = Initial())
    Constraint(_sv_target, good; equals = [2.0, 2.0],      at = Final())
    Constraint(c -> [state(c).v], good; upper_bound = 10.0, at = Path())      # no partial: AD
    Objective(_sv_duration, good; sense = Min())
    initialize!(Sequence(good))

    printed = mktemp() do path, io
        redirect_stdout(io) do
            @test check_partials(good) < 1e-6
        end
        close(io)
        read(path, String)
    end
    @test occursin("_sv_dynamics!", printed)
    @test occursin("fell back to AD", printed)
    @test check_partials(good; verbose = false) < 1e-6

    bad = _sv_phase(:bad, (0.0, 1.0), (0.0, 0.0), (2.0, 2.0))
    Vary(final_time, bad; lower_bound = 0.1, upper_bound = 10.0)
    Constraint(_sv_wrong_target, bad; equals = [2.0, 2.0], at = Final())
    Objective(_sv_duration, bad; sense = Min())
    initialize!(Sequence(bad))
    worst = @test_logs (:warn, r"disagrees with finite differences") match_mode = :any begin
        check_partials(bad; verbose = false)
    end
    @test worst ≈ 1.0 atol = 1e-6
end

# ─────────────────────────────────────────────────────────────────────────────
# Undeclared partials: the automatic-differentiation fallbacks
# ─────────────────────────────────────────────────────────────────────────────

# The brachistochrone dynamics again, with no @partial at all.
function _sv_dynamics_bare!(dy, y::_SvState, u::_SvControl, p, t, model)
    dy[1] = y.v * sin(u.θ)
    dy[2] = y.v * cos(u.θ)
    dy[3] = model.g * cos(u.θ)
end

# Inactive at the optimum, and reading the state, the control and the node time, so every block
# of its Jacobian has to come from differentiation.
_sv_loose_cap(c) = [state(c).v * cos(control(c).θ)^2 + 1e-3 * c.t]

@testset "undeclared partials — the fallbacks reach the same optimum" begin
    p = CollocationPhase(name = :bare, transcription = HermiteSimpson(n_steps = 20),
                         dynamics = _sv_dynamics_bare!, model = _SvModel(_SV_G),
                         state = _SvState, control = _SvControl, tspan = (0.0, 1.0))
    Vary(state, p; guess = [0.0 2.0; 0.0 2.0; 0.0 sqrt(4_SV_G)],
         lower_bound = [-Inf, -Inf, 0.0], upper_bound = [Inf, Inf, Inf])
    Vary(control, p; guess = reshape([0.5, 1.0], 1, 2), lower_bound = [-π/2], upper_bound = [π/2])
    Vary(final_time, p; lower_bound = 0.1, upper_bound = 10.0)
    Constraint(c -> [state(c).x, state(c).y, state(c).v], p; equals = [0.0, 0.0, 0.0],
               at = Initial())
    Constraint(c -> [state(c).x, state(c).y], p; equals = [2.0, 2.0], at = Final())
    Constraint(_sv_loose_cap, p; upper_bound = 100.0, at = Path())
    Objective(c -> final_time(c), p; sense = Min())

    @test solve!(Sequence(p); method = Optimize(print_level = 0)).info === :Solve_Succeeded
    @test get_final_time(p) ≈ 0.824479 atol = 1e-5
end

# ─────────────────────────────────────────────────────────────────────────────
# A ForceModel as a phase's dynamics
# ─────────────────────────────────────────────────────────────────────────────

# A thruster written the additive way a user force may be written: it adds to the buffer rather
# than overwriting it, and it writes a seventh, mass, row.
struct _SvThrust <: AstroProp.OrbitODE
    accel::Float64
end
function AstroProp.accel_eval!(f::_SvThrust, t::Time, x, dx, sc, params)
    dx[4] += f.accel
    length(dx) >= 7 && (dx[7] -= 0.1)
    return dx
end

# The same thruster written the way the built-in forces are: every row it owns is overwritten.
struct _SvThrustOverwrite <: AstroProp.OrbitODE
    accel::Float64
end
function AstroProp.accel_eval!(f::_SvThrustOverwrite, t::Time, x, dx, sc, params)
    dx[1] = x[4]; dx[2] = x[5]; dx[3] = x[6]
    dx[4] = f.accel; dx[5] = 0.0; dx[6] = 0.0
    return dx
end

@testset "forcemodel_rhs — forces summed, whichever way each one writes" begin
    t0 = Time("2020-10-20T12:00:00", UTC(), ISOT())
    sc = Spacecraft(state = CartesianState([7000.0, 300.0, 1200.0, -0.4, 7.4, 0.9]), time = t0,
                    mass = 1000.0, srp = SphericalSRP(c_r = 1.8, srp_area = 10.0))
    y  = to_posvel(sc)
    fm = ForceModel(PointMassGravity(earth, (moon, sun)), SolarRadiationPressure(earth))

    rhs! = AstroSolve.forcemodel_rhs(fm, t0, 6, sc)
    dy = zeros(6)
    rhs!(dy, y, nothing, nothing, 0.0, nothing)
    @test dy ≈ AstroProp._eval_all!(fm, t0, y, zeros(6), sc) rtol = 1e-14

    # An additive force after a built-in one, with a mass row: gravity once, thrust once.
    thrust = ForceModel(PointMassGravity(earth, ()), _SvThrust(1e-6))
    y7 = vcat(y, 1000.0)
    dy7 = zeros(7)
    AstroSolve.forcemodel_rhs(thrust, t0, 7, sc)(dy7, y7, nothing, nothing, 0.0, nothing)
    grav = AstroProp._eval_all!(ForceModel(PointMassGravity(earth, ())), t0, y, zeros(6), sc)
    @test dy7[1:6] ≈ grav .+ [0, 0, 0, 1e-6, 0, 0] rtol = 1e-14
    @test dy7[7] == -0.1

    # propagate! gives the same trajectory whichever way the thruster writes. The overwriting form
    # is how the built-in forces are written; before the buffer was reset per force, the additive
    # form counted gravity twice.
    integ = IntegratorConfig(Vern9(); abstol = 1e-12, reltol = 1e-12, dt = 60.0)
    finals = map((_SvThrust(1e-6), _SvThrustOverwrite(1e-6))) do thruster
        sc_t = Spacecraft(state = CartesianState(y), time = t0)
        propagate!(OrbitPropagator(ForceModel(PointMassGravity(earth, ()), thruster), integ),
                   sc_t, StopAt(sc_t, PropDurationSeconds(), 600.0))
        to_posvel(sc_t)
    end
    @test finals[1] ≈ finals[2] rtol = 1e-12

    # A ForceModel needs the spacecraft that supplies its epoch.
    p = _sv_phase(:fm, (0.0, 1.0), (0.0, 0.0), (1.0, 1.0))
    @test_throws ArgumentError set_dynamics!(p, fm)
end

nothing
