# Copyright (C) 2025 Gen Astro LLC
# SPDX-License-Identifier: LicenseRef-GenAstro-SourceAvailable-1.0

# Orbit determination through the model-based entry point.
#
# This is the path a user takes: an ODProblem holding a spacecraft, a propagator and the
# measurements, `Vary(state, sc; ...)` to say what is estimated, and observation records in.
# No physics or geometry is written by the caller, which is the whole claim of the interface.
#
# The truth is self-generated rather than analytic, which is the weakest kind of
# truth — but it is generated by *propagating* a known initial state and
# evaluating the range geometry, then recovered by an estimator that does not share that code
# path. A bug in the propagator or the predictor would have to appear identically in both
# directions to survive, and the cross-checks below are what make that unlikely: the same data
# is fit from several starting errors, and the residuals must collapse to the noise floor.
#
# The state assertions are written against the covariance the fit reports, not against an
# absolute number picked by hand. A single station over a short arc is weakly observable, so an
# absolute tolerance states something about the geometry rather than about the estimator:
# thirty minutes of range-only data fits its residuals to 2e-5 km while the state sits 0.245 km
# away along a near-null direction, which is correct behaviour and would fail a metre-level
# check. Checking the error against the reported sigma tests covariance realism instead, which
# is the property an operator relies on. A loose absolute bound sits alongside it so the pair
# cannot both pass on a covariance that is merely self-consistent and wrong.
#
# Covers the model-based halves of BatchLeastSquares.jl — build_od_closures, the ODProblem
# entry point, and the range and Doppler predictors.

using AstroSolve
using AstroModels
using AstroProp
using AstroStates
using AstroEpochs
using AstroFrames
using AstroUniverse
using EpicycleBase
using LinearAlgebra
using OrdinaryDiffEqHighOrderRK: DP8
using Test

const _OD_BLS = AstroSolve.BatchLeastSquares

# A low Earth orbit, and one station that sees it.
const _OD_T0    = Time("2020-03-01T00:00:00.000", TT(), ISOT())
const _OD_TRUTH = [6878.137, 0.0, 0.0, 0.0, 4.71754, 5.99820]

const _OD_SIG_R = 1e-3      # range sigma, km
const _OD_SIG_D = 1e-6      # range-rate sigma, km/s

_od_station() = GroundStation(name = "DSS-14", body = earth,
                              latitude = 35.4267, longitude = -116.89,
                              altitude = 1.0, min_elevation = 0.0)

_od_prop() = OrbitPropagator(ForceModel(PointMassGravity(earth, ())),
                             IntegratorConfig(DP8(); dt = 60.0,
                                              reltol = 1e-12, abstol = 1e-12))

_od_sc(y0) = Spacecraft(state = CartesianState(copy(y0)), time = _OD_T0,
                        coord_sys = CoordinateSystem(earth, ICRF()),
                        name = "Sat")

# `propagate!` leaves the spacecraft epoch tagged `jd`, while a spacecraft built from a date
# string is tagged `isot`, and `-(::Time, ::Time)` refuses a difference across the two even
# though both store the same `jd1 + jd2`. Records read from a TDM carry `isot`, so relabel the
# generated epochs to match rather than handing the estimator data no file would produce. The
# numbers are untouched; only the tag changes.
_od_as_isot(t) = AstroEpochs._time_jd(t.jd1, t.jd2, t.scale, :isot)   # Julian-date parts, shown as ISOT

# The measurements a single station reports, which is what a TDM from that station carries.
_od_specs(gs, sc) = AbstractMeasurement[
    TwoWayRange(  SignalPath(gs, sc, gs); noise = MeasurementNoise(_OD_SIG_R)),
    TwoWayDoppler(SignalPath(gs, sc, gs); noise = MeasurementNoise(_OD_SIG_D))]

"""Propagate the truth step by step and read range and range rate to `gs` at each stop.

There is no interpolate-at-epoch accessor, so the truth is marched forward one interval at a
time and the state is read where the propagation stops. That also keeps the observation epochs
exactly at integrator stopping points rather than interpolated between them.
"""
function _od_truth_records(offsets_s)
    gs   = _od_station()
    sc   = _od_sc(_OD_TRUTH)
    prop = _od_prop()

    recs = AstroSolve.ObservationRecord[]
    prev = 0.0
    for dt in offsets_s
        propagate!(prop, sc, StopAt(sc, PropDurationSeconds(), dt - prev))
        prev = dt
        t    = _od_as_isot(sc.time)
        y    = to_posvel(sc)
        path = SignalPath(gs, sc, gs)
        rho    = _OD_BLS._predict(TwoWayRange(path;   noise = MeasurementNoise(_OD_SIG_R)),
                                  y, sc.time, sc)
        rhodot = _OD_BLS._predict(TwoWayDoppler(path; noise = MeasurementNoise(_OD_SIG_D)),
                                  y, sc.time, sc)
        push!(recs, AstroSolve.ObservationRecord(:RANGE,   t, rho,    "DSS-14"))
        push!(recs, AstroSolve.ObservationRecord(:DOPPLER, t, rhodot, "DSS-14"))
    end
    return gs, recs
end

# One orbital period at one-minute spacing. A shorter arc leaves the along-track and
# cross-track directions nearly unobservable from one station; see the note at the top.
const _OD_OFFSETS = collect(60.0:60.0:5400.0)

@testset "OD batch — recovers the truth state from range data" begin
    gs, recs = _od_truth_records(_OD_OFFSETS)

    # Start a kilometre and a metre per second away, which is a realistic initial error for a
    # first fit and well inside the linear regime.
    guess = _OD_TRUTH .+ [1.0, -1.0, 0.5, 1e-3, -1e-3, 5e-4]
    sc    = _od_sc(guess)
    y0    = Vary(state, sc; guess = guess,
                 covariance = Diagonal([1e2, 1e2, 1e2, 1e-2, 1e-2, 1e-2]))

    problem = ODProblem(spacecraft = sc, propagator = _od_prop(),
                        measurements = _od_specs(gs, sc),
                        solve_for = [y0])

    res = _OD_BLS.solve_batch_ls!([y0], recs; model = problem, n_iters = 10)

    # The formal covariance is a covariance.
    @test res.P_hat ≈ res.P_hat' atol = 1e-10
    @test isposdef(Symmetric(res.P_hat))
    @test res.sigma ≈ sqrt.(diag(res.P_hat)) atol = 1e-12
    @test all(res.sigma .> 0)

    # Every component lands inside three times the uncertainty the fit reports. This catches a
    # covariance scaled wrongly or an estimate that stopped early, and it does not encode a
    # tolerance the geometry cannot deliver.
    err = abs.(res.X_hat .- _OD_TRUTH)
    @test all(err .<= 3 .* res.sigma)

    # The uncertainty itself is small, so the check above cannot be satisfied by a fit that
    # reports huge sigmas and learned nothing. One orbit of range and Doppler from one station
    # gives metres in position and millimetres per second in velocity.
    @test norm(res.X_hat[1:3] .- _OD_TRUTH[1:3]) < 5e-2
    @test norm(res.X_hat[4:6] .- _OD_TRUTH[4:6]) < 5e-5

    # Noise-free data leaves residuals at the level the geometry and integrator can hold, not
    # at the assumed measurement sigma.
    @test maximum(abs, reduce(vcat, res.residuals)) < 1e-3

    # And the estimate is written back onto the spacecraft, which is where a user reads it.
    @test norm(to_posvel(sc)[1:3] .- _OD_TRUTH[1:3]) < 5e-2
end

@testset "OD batch — the answer does not depend on the starting error" begin
    # Several starting errors, one answer. This is what makes a self-generated truth credible:
    # the estimator finds the same state from different directions, so it is solving the
    # problem rather than returning its input.
    gs, recs = _od_truth_records(_OD_OFFSETS)

    answers = map(([2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                   [0.0, -3.0, 1.0, 0.0, 2e-3, 0.0],
                   [-1.0, 1.0, -1.0, 1e-3, -1e-3, 1e-3])) do err
        guess = _OD_TRUTH .+ err
        sc    = _od_sc(guess)
        y0    = Vary(state, sc; guess = guess,
                     covariance = Diagonal([1e4, 1e4, 1e4, 1e0, 1e0, 1e0]))
        problem = ODProblem(spacecraft = sc, propagator = _od_prop(),
                            measurements = _od_specs(gs, sc),
                            solve_for = [y0])
        _OD_BLS.solve_batch_ls!([y0], recs; model = problem, n_iters = 12).X_hat
    end

    for a in answers
        @test norm(a[1:3] .- _OD_TRUTH[1:3]) < 1e-1
    end
    @test norm(answers[1] .- answers[2]) < 1e-1
    @test norm(answers[2] .- answers[3]) < 1e-1
end

@testset "OD batch — Doppler and range predictors agree with geometry" begin
    # The predictors are the part of this path a caller never writes, so they are worth
    # checking directly against the geometry rather than only through a converged fit.
    gs   = _od_station()
    sc   = _od_sc(_OD_TRUTH)
    prop = _od_prop()
    propagate!(prop, sc, StopAt(sc, PropDurationSeconds(), 300.0))

    t = sc.time
    y = to_posvel(sc)
    path = SignalPath(gs, sc, gs)

    rho    = _OD_BLS._predict(TwoWayRange(path;   noise = MeasurementNoise(0.0)), y, t, sc)
    rhodot = _OD_BLS._predict(TwoWayDoppler(path; noise = MeasurementNoise(0.0)), y, t, sc)

    # Two-way range over an out-and-back path is twice the one-way distance, and the path sums
    # legs rather than doubling implicitly, so this is a real check on the summation.
    r_gs = get_state(gs, t)[1]
    one_way = norm(y[1:3] .- r_gs)
    @test rho ≈ 2 * one_way atol = 1e-9

    # Range rate is the time derivative of that, so it equals the projection of relative
    # velocity on the line of sight, doubled.
    v_gs = get_state(gs, t)[2]
    los  = (y[1:3] .- r_gs) ./ one_way
    @test rhodot ≈ 2 * dot(y[4:6] .- v_gs, los) atol = 1e-9

    # A one-participant path cannot be a measurement, and says so.
    @test_throws ArgumentError _OD_BLS._predict(
        TwoWayRange(SignalPath(gs); noise = MeasurementNoise(0.0)), y, t, sc)
end

@testset "OD batch — closures and schedule come off the model" begin
    # build_od_closures is what turns records plus a model into the low-level estimator's
    # arguments. Its job is to need nothing from the caller, so the shapes it produces are the
    # contract worth asserting.
    gs, recs = _od_truth_records(_OD_OFFSETS[1:5])   # five epochs, range and Doppler at each
    sc = _od_sc(_OD_TRUTH)
    problem = ODProblem(spacecraft = sc, propagator = _od_prop(),
                        measurements = _od_specs(gs, sc),
                        solve_for = Any[])

    dyn, meas, obs_times, obs_data, R_per_obs = _OD_BLS.build_od_closures(recs, problem)

    @test length(obs_times) == 10
    @test length(obs_data)  == 10
    @test length(R_per_obs) == 10

    # Times are seconds since the spacecraft epoch, in order. Differencing two epochs held as a
    # Julian day pair resolves to a few microseconds near JD 2.45e6, so the first offset comes
    # back as 59.99999642 rather than exactly 60; the tolerance is that resolution, not slack.
    @test issorted(obs_times)
    @test obs_times[1] ≈ 60.0 atol = 1e-4

    # Each record is one scalar observation, and R is the sigma squared of its own spec — read
    # off the measurement rather than supplied by the caller. Two kinds, two variances.
    @test all(length(d) == 1 for d in obs_data)
    @test all(size(R) == (1, 1) for R in R_per_obs)
    @test sort(unique(R[1, 1] for R in R_per_obs)) ≈ sort([_OD_SIG_R^2, _OD_SIG_D^2])

    # An empty record stream is refused, naming what is needed.
    @test_throws ArgumentError _OD_BLS.build_od_closures(AstroSolve.ObservationRecord[], problem)

    # Records whose kind has no matching measurement on the model are refused too, since the
    # alternative is silently dropping data. This model has range but no Doppler spec.
    range_only = ODProblem(spacecraft = sc, propagator = _od_prop(),
                           measurements = AbstractMeasurement[
                               TwoWayRange(SignalPath(gs, sc, gs);
                                           noise = MeasurementNoise(_OD_SIG_R))],
                           solve_for = Any[])
    @test_throws ArgumentError _OD_BLS.build_od_closures(copy(recs), range_only)
end
