# Copyright (C) 2025 Gen Astro LLC
# SPDX-License-Identifier: MIT

# =============================================================================
# The lunar frames, MOON_PA and MOON_ME.
#
# These were implemented and then never exercised — this file is the first
# thing to run them.
#
# As with the ephemeris rows, two kinds of test live here and they are not
# equally strong. `axes_rotation(ICRF(), MoonPA(), e)` calls SPICE `sxform`, so
# comparing it against `sxform` is circular.
#
# **The physical checks are independent.** The Moon's rotation is synchronous,
# which is a fact about the Moon and not about any kernel:
#
#   - Earth, seen from the Moon and expressed in principal axes, stays within
#     the libration of the +X axis. This is the strongest test in the file:
#     it uses the orientation *and* the ephemeris together, so it fails if
#     either is wrong, or if the two disagree about the epoch.
#   - the prime meridian turns once per sidereal month.
#   - ME differs from PA by a fixed rotation, whose angles are published.
#
# **The regression rows are circular**, and earn their place on one specific
# failure: a consistent but older set of lunar kernels.
#
# Mismatched kernels are not the risk. Pairing `moon_080317.tf`, which aliases
# MOON_PA to the DE421 frame, with DE440 orientation data raises loudly —
# "PCK data required ... for MOON_PA_DE421 were not found".
#
# The quiet case is `moon_pa_de421_1900-2050.bpc` *with* `moon_080317.tf`. That
# pair is internally consistent, loads without complaint, and returns a
# rotation orthonormal to 3e-16 with determinant exactly 1. It differs from
# DE440 by 0.178 arcsec — 1.5 m on the lunar surface. Every structural check
# passes, and so does the synchronous-rotation check above, at 8.777° against
# a 15° bound. Only these rows notice. Both DE421 files are commonly already
# cached, so this is a live way to be quietly wrong rather than a hypothetical.
#
# The generator is `generate_moon_truth.jl`, internal SPICE truth tooling.
#
# Truth source: SPICE `sxform("J2000", frame, et)` reading
# `moon_pa_de440_200625.bpc` with `moon_de440_250416.tf`.
# =============================================================================

using AstroFrames
using AstroUniverse
using LinearAlgebra
using Test

# The lunar kernels are defaults, fetched and loaded by AstroUniverse at
# startup, so these tests name a frame and it works — which is the whole point
# of them being defaults. Nothing to set up here.

# Generated by `generate_moon_truth.jl`, internal SPICE truth tooling
# -- do not hand-edit.
#
# Source: SPICE sxform("J2000", frame, et), reading:
#   naif0012.tls
#   epicycle_de440_1950-2100.bsp
#   moon_pa_de440_200625.bpc
#   moon_de440_250416.tf

const _MOON_TRUTH = (
    (jd_tdb = 2451545.0,
        pa = (
            R = [0.78404492829350736 0.55823610180457883 0.27137797452862089
                 -0.62030307673981189 0.72039589568409101 0.31024804023335795
                 -0.022307922457100365 -0.41158499501748613 0.91109831987118928],
            Ṙ = [-1.651239562660884e-06 1.9173511883056798e-06 8.2656432137258302e-07
                 -2.0870974900763917e-06 -1.4860132066849255e-06 -7.2237419889446474e-07
                 -5.8319870689312126e-10 -4.4501592685073889e-10 -2.1531356746849344e-10],
        ),
        me = (
            R = [0.78424037193118157 0.55784202210057199 0.27162348464738273
                 -0.62004509426615506 0.72058004932922781 0.31033606555661991
                 -0.022607965625347233 -0.41179688061887104 0.91099517507111449],
            Ṙ = [-1.6505530068549005e-06 1.9178396121475199e-06 8.2680176559332817e-07
                 -2.087640566800871e-06 -1.4853823953716274e-06 -7.2210225358211424e-07
                 4.3703528853261807e-11 -1.1787180708482143e-09 -5.3173100152649378e-10],
        ),
    ),
    (jd_tdb = 2458849.5,
        pa = (
            R = [-0.96575783024995654 0.24712594724863907 0.078997338609340981
                 -0.25796808326787313 -0.88221833656598403 -0.39388231064855894
                 -0.02764563846243526 -0.4007737177301065 0.9157598734661796],
            Ṙ = [-6.8669455666807752e-07 -2.3484083045749099e-06 -1.0484912499036975e-06
                 2.5708550412700079e-06 -6.5683015945015485e-07 -2.1257856576909384e-07
                 -6.4756195733244533e-10 -2.2082688534864247e-09 -9.8597722839309393e-10],
        ),
        me = (
            R = [-0.96568339427162064 0.24726322557876182 0.079476281395318399
                 -0.25828572690275514 -0.88213645335068191 -0.39385753889978492
                 -0.027277560491306533 -0.40086927413592893 0.91572908643734618],
            Ṙ = [-6.8754042161875573e-07 -2.3481927791281544e-06 -1.0484215634762339e-06
                 2.5706290085506152e-06 -6.576026514388493e-07 -2.1292346377523941e-07
                 -3.8177985404779882e-10 -1.3132715019080737e-09 -5.8626969998858273e-10],
        ),
    ),
    (jd_tdb = 2469854.0,
        pa = (
            R = [0.099483031895125806 0.90804615669665756 0.40688487766613124
                 -0.99479490967048667 0.081701654728140657 0.060892752511049551
                 0.022050262099159289 -0.41082480076440481 0.9114476227508882],
            Ṙ = [-2.6478169871123672e-06 2.1726152911330849e-07 1.6252598437988438e-07
                 -2.6485143747577848e-07 -2.4158267431329032e-06 -1.0854464060787673e-06
                 -2.7210578355122131e-09 -2.2770276015518678e-10 -3.6805079937558724e-11],
        ),
        me = (
            R = [0.09981867831313207 0.90786242663716121 0.40721253143819702
                 -0.99476215975824422 0.082000915140075306 0.061025367096836307
                 0.022010837624518543 -0.41117108874126274 0.91129241125469262],
            Ṙ = [-2.6477305641089886e-06 2.180561217955773e-07 1.6288301670865513e-07
                 -2.6572244322106135e-07 -2.4157551419317765e-06 -1.0853928828804389e-06
                 -1.7112513762581813e-09 -3.1415758516088883e-10 -1.0041391656426428e-10],
        ),
    ),
)

const _MOON_EPOCHS = (2451545.0, 2458849.5, 2469854.0)

# --- the regression rows -----------------------------------------------------

@testset "lunar frames still match SPICE" begin
    for case in _MOON_TRUTH
        @testset "jd $(case.jd_tdb)" begin
            for (axes, truth) in ((MoonPA(), case.pa), (MoonME(), case.me))
                M = Matrix(axes_rotation(ICRF(), axes, case.jd_tdb))
                @test norm(M[1:3, 1:3] - truth.R) < 1e-13
                @test norm(M[4:6, 1:3] - truth.Ṙ) / norm(truth.Ṙ) < 1e-12
            end
        end
    end
end

# --- the physical checks -----------------------------------------------------

@testset "the Moon's rotation is synchronous" begin
    # The near side faces Earth. In principal axes the +X axis is the mean
    # Earth direction, so the true direction stays within the libration in
    # longitude and latitude — measured 4.5° to 8.8° over a year, sampled
    # weekly. The bound is 15°, comfortably above the libration and far below
    # anything a wrong epoch scale, a wrong frame, or a PA/ME mix-up produces.
    #
    # This is the one test here that consults the orientation and the ephemeris
    # at once. A 1-day epoch slip moves the Moon 13° in its orbit while the
    # frame rotates with it, so a disagreement between the two shows up
    # immediately.
    angles = Float64[]
    for jd in 2458849.5:7.0:(2458849.5 + 364.0)
        earth_icrf = translate(moon, earth, jd)
        R = Matrix(axes_rotation(ICRF(), MoonPA(), jd))[1:3, 1:3]
        earth_pa = R * earth_icrf
        push!(angles, rad2deg(acos(clamp(earth_pa[1] / norm(earth_pa), -1, 1))))
    end

    @test maximum(angles) < 15.0
    # And it is genuinely librating, not pinned at zero by some identity.
    @test maximum(angles) - minimum(angles) > 1.0
end

@testset "the prime meridian turns once per sidereal month" begin
    # From the rate block: Ṙ·Rᵀ is the skew-symmetric angular velocity, whose
    # magnitude is the spin rate. The sidereal month is 27.32166 days, and the
    # instantaneous rate varies about it with the libration — measured 27.319
    # to 27.322. This checks the rate block carries a real derivative in the
    # right units, which no orthonormality check can see.
    for jd in _MOON_EPOCHS
        M = Matrix(axes_rotation(ICRF(), MoonPA(), jd))
        Ω = M[4:6, 1:3] * M[1:3, 1:3]'
        rate = norm((Ω[3, 2], Ω[1, 3], Ω[2, 1]))
        period_days = 2π / rate / 86_400
        @test abs(period_days - 27.32166) < 0.01
    end
end

@testset "ME is a fixed rotation from PA" begin
    # The mean-Earth frame is defined as a constant offset from the principal
    # axes. "Constant" is testable: the same matrix at every epoch.
    offsets = [Matrix(axes_rotation(ICRF(), MoonME(), jd))[1:3, 1:3] *
               Matrix(axes_rotation(ICRF(), MoonPA(), jd))[1:3, 1:3]'
               for jd in _MOON_EPOCHS]

    for offset in offsets[2:end]
        @test maximum(abs.(offset - offsets[1])) < 1e-12
    end

    # And it is the published rotation. Read as a rotation vector, the three
    # components are the DE440 constants in arcseconds — 67.8526, 78.6944 and
    # 0.2914 — which is what the frame kernel encodes. A wrong or missing frame
    # kernel changes these.
    D = offsets[1]
    components = rad2deg.((0.5 * (D[3,2] - D[2,3]),
                           0.5 * (D[1,3] - D[3,1]),
                           0.5 * (D[2,1] - D[1,2]))) .* 3600

    @test abs(components[1] -  0.2914) < 1e-3
    @test abs(components[2] - 78.6944) < 1e-3
    @test abs(components[3] - 67.8526) < 1e-3

    # Total offset, about 104 arcsec — roughly a kilometre on the surface.
    @test abs(norm(components) - 103.907982) < 1e-3
end

# --- structure and routing ---------------------------------------------------

@testset "lunar frames are well formed and route" begin
    for jd in _MOON_EPOCHS
        for axes in (MoonPA(), MoonME())
            M = Matrix(axes_rotation(ICRF(), axes, jd))
            R = M[1:3, 1:3]

            @test size(M) == (6, 6)
            @test norm(R' * R - I) < 1e-14
            @test isapprox(det(R), 1; atol = 1e-14)
            @test all(iszero, M[1:3, 4:6])       # block form [R 0; Ṙ R]
            @test M[4:6, 4:6] == R

            # The reverse edge is the transpose, in both blocks.
            B = Matrix(axes_rotation(axes, ICRF(), jd))
            @test norm(B[1:3, 1:3] - R') < 1e-14
            @test norm(B[4:6, 1:3] - M[4:6, 1:3]') < 1e-14

            # Round trip through the hub.
            @test norm(Matrix(B * M) - I) < 1e-13
        end

        # PA and ME are not the same frame, and both reach the Earth chain
        # through the ICRF hub rather than needing an edge of their own.
        Rpa = Matrix(axes_rotation(ICRF(), MoonPA(), jd))[1:3, 1:3]
        Rme = Matrix(axes_rotation(ICRF(), MoonME(), jd))[1:3, 1:3]
        @test norm(Rpa - Rme) > 1e-8

        for target in (MJ2000Eq(), GCRF())
            M = Matrix(axes_rotation(MoonPA(), target, jd))
            @test norm(M[1:3, 1:3]' * M[1:3, 1:3] - I) < 1e-13
        end
    end
end

@testset "the lunar kernels are loaded without being asked for" begin
    # The reason the tests above need no setup, asserted rather than assumed:
    # naming a frame Epicycle offers is all a user should have to do.
    for kernel in ("moon_pa_de440_200625.bpc", "moon_de440_250416.tf")
        @test kernel in AstroUniverse.DEFAULT_KERNELS
    end
end
