# Copyright (C) 2025 Gen Astro LLC
# SPDX-License-Identifier: MIT

# =============================================================================
# The Earth chains against ERFA — external truth, the strongest check here.
#
# Everything else in this suite is analytic, structural, or cross-branch
# agreement: it can tell you a rotation is orthonormal and turns at the right
# rate, but not that it is the rotation the IAU defines. This file can.
#
# The truth is ERFA — the community C translation of IAU SOFA, the IAU's own
# reference implementation — reached through `pyerfa`. Epicycle's Earth chain
# runs through SatelliteToolboxTransformations, an independent Julia
# implementation, so agreement between them is a real check rather than a
# circular one.
#
# **The numbers are in this file on purpose.** Generating them needs Python,
# ERFA, and a matching set of EOP; doing that on every test run would make the
# test depend on a toolchain, a network, and a data file that could silently
# change underneath it. Truth data that can move is not truth data. The
# generator is internal AstroPy truth tooling, not shipped, and regenerating is a
# deliberate act — see that directory's README for the pipeline and for why
# astropy's frame classes are bypassed in favour of ERFA primitives.
#
# The EOP values below are Epicycle's own, fed to the generator, so this
# compares transformation code and nothing else. UT1−UTC reaches 0.9 s — 13
# arcseconds of Earth rotation — so a truth source using its own IERS table
# would measure table drift instead.
#
# Tolerances are not round numbers chosen for comfort. Each is set from the
# measured agreement and, where a residual is understood, just above the effect
# that explains it, so a row stays pinned at its explained value rather than
# being given a blanket allowance.
# =============================================================================

using AstroFrames
using AstroUniverse
using AstroEpochs
using LinearAlgebra
using Test

# Generated by `emit_julia_truth.jl`, internal AstroPy truth tooling — do not
# hand-edit.
# Source: ERFA (IAU SOFA) via pyerfa 2.0.1.5, numpy 2.5.2, Python 3.13.14.
# EOP values are Epicycle's own, fed to the generator, so the
# comparison is of transformation code and nothing else.

const _TRUTH = (
    (
        jd_utc = 2451545,
        jd_tdb = 2451545.0007428695,
        eop = (dut1_s = 0.35503960000000001, xp_as = 0.043421000000000001, yp_as = 0.37775249999999999),
        mean_obliquity = 0.40909280421771277,
        true_obliquity = 0.40906479917120597,
        matrices = (
            ICRF_to_MJ2000Eq = [
                0.99999999999999423  -7.078279744199198e-08  8.0562171469761338e-08
                7.0782794778573375e-08  0.99999999999999689  3.3060414542221364e-08
                -8.0562173809869717e-08  -3.3060408839805517e-08  0.99999999999999623
            ],
            MJ2000Eq_to_MODEq = [
                1  -4.5480796127177868e-10  -1.9763450693892384e-10
                4.5480796127177868e-10  1  -4.4942873589079689e-20
                1.9763450693892384e-10  -4.4942873588765462e-20  1
            ],
            MODEq_to_TODEq = [
                0.99999999770518178  6.2156524571944184e-05  2.6948151455698992e-05
                -6.2157279231804733e-05  0.99999999767611836  2.8004208991239121e-05
                -2.6946410748770397e-05  -2.800588395079906e-05  0.99999999924478056
            ],
            TODEq_to_PEF = [
                0.1815240003412093  -0.98338651470320892  0
                0.98338651470320892  0.1815240003412093  0
                0  0  1
            ],
            PEF_to_ITRF = [
                0.9999999999999778  0  2.1051094847457006e-07
                3.8552886704449613e-13  0.99999999999832301  -1.8313958007322354e-06
                -2.1051094847421703e-07  1.831395800732276e-06  0.9999999999983008
            ],
            ICRF_to_ITRF_fk5 = [
                0.18158505449766349  -0.98337524245776575  -2.2454632062883029e-05
                0.98337524238960183  0.18158505380375933  2.9837520755221357e-05
                -2.526405363572219e-05  -2.7499377080068656e-05  0.99999999930275574
            ],
            GCRF_to_CIRS = [
                0.99999999963695085  9.7566427159634372e-09  2.6946205625859831e-05
                -1.0511295833737222e-08  0.99999999960783414  2.8005916424007288e-05
                -2.694620534204873e-05  -2.8005916697079306e-05  0.99999999924478533
            ],
            CIRS_to_TIRS = [
                0.18158511385475562  -0.98337523175355368  0
                0.98337523175355368  0.18158511385475562  0
                0  0  1
            ],
            TIRS_to_ITRF = [
                0.9999999999999778  -4.6344216489415034e-18  2.1051094847457006e-07
                3.8553350146614505e-13  0.99999999999832301  -1.8313958007322354e-06
                -2.1051094847421703e-07  1.831395800732276e-06  0.9999999999983008
            ],
            GCRF_to_ITRF_iau2006 = [
                0.18158512411970279  -0.98337522960212009  -2.2436783789087317e-05
                0.9833752295356154  0.18158512342859121  2.9752292925258118e-05
                -2.5183481732883208e-05  -2.7466351212313468e-05  0.99999999930569583
            ],
        ),
    ),
    (
        jd_utc = 2455197.5,
        jd_tdb = 2455197.5007660175,
        eop = (dut1_s = 0.11407829999999999, xp_as = 0.098698999999999995, yp_as = 0.19286700000000001),
        mean_obliquity = 0.40907010764527341,
        true_obliquity = 0.40908375263350477,
        matrices = (
            ICRF_to_MJ2000Eq = [
                0.99999999999999423  -7.078279744199198e-08  8.0562171469761338e-08
                7.0782794778573375e-08  0.99999999999999689  3.3060414542221364e-08
                -8.0562173809869717e-08  -3.3060408839805517e-08  0.99999999999999623
            ],
            MJ2000Eq_to_MODEq = [
                0.99999702751862585  -0.0022362381329873197  -0.00097169590157658125
                0.0022362381329691736  0.99999749961579021  -1.0864920037227808e-06
                0.00097169590161834212  -1.0864546546098755e-06  0.99999952790283575
            ],
            MODEq_to_TODEq = [
                0.99999999684802365  -7.2846439382638793e-05  -3.1580832612726871e-05
                7.2846008455767987e-05  0.99999999725362099  -1.3646138499689986e-05
                3.1581826598594966e-05  1.3643837919075086e-05  0.99999999940821693
            ],
            TODEq_to_PEF = [
                -0.18296099755011061  0.98312017239779415  0
                -0.98312017239779415  -0.18296099755011061  0
                0  0  1
            ],
            PEF_to_ITRF = [
                0.99999999999988554  0  4.7850625511828273e-07
                4.4742516954311276e-13  0.99999999999956279  -9.3504560234528555e-07
                -4.7850625511807352e-07  9.3504560234539259e-07  0.99999999999944833
            ],
            ICRF_to_ITRF_fk5 = [
                -0.18069025367765967  0.98354003654883837  0.00016950343054020439
                -0.98353954034974544  -0.18069033279602748  0.00098802969182367373
                0.0010023943904819712  1.1814009495458809e-05  0.99999949753283124
            ],
            GCRF_to_CIRS = [
                0.99999949668622345  -1.4030622153687888e-08  -0.001003308177834657
                1.5030951084488153e-09  0.99999999992204713  -1.2486221162378655e-05
                0.0010033081779316359  1.2486213369823914e-05  0.99999949660827059
            ],
            CIRS_to_TIRS = [
                -0.18069041620804324  0.98354002129581086  0
                -0.98354002129581086  -0.18069041620804324  0
                0  0  1
            ],
            TIRS_to_ITRF = [
                0.99999999999988554  -2.2786247790976941e-11  4.7850625511828273e-07
                2.3233672960512699e-11  0.99999999999956279  -9.3504560234528555e-07
                -4.7850625509676736e-07  9.3504560235629592e-07  0.99999999999944833
            ],
            GCRF_to_ITRF_iau2006 = [
                -0.18069032328319218  0.98354002376431948  0.00016948598000161364
                -0.98353952748007023  -0.18069040238302445  0.00098811484196429885
                0.0010024749850722162  1.1846629550165791e-05  0.99999949745165451
            ],
        ),
    ),
    (
        jd_utc = 2458849.5,
        jd_tdb = 2458849.5008007395,
        eop = (dut1_s = -0.17715539999999999, xp_as = 0.076577000000000006, yp_as = 0.28233599999999998),
        mean_obliquity = 0.40904741417528212,
        true_obliquity = 0.40903910609411021,
        matrices = (
            ICRF_to_MJ2000Eq = [
                0.99999999999999423  -7.078279744199198e-08  8.0562171469761338e-08
                7.0782794778573375e-08  0.99999999999999689  3.3060414542221364e-08
                -8.0562173809869717e-08  -3.3060408839805517e-08  0.99999999999999623
            ],
            MJ2000Eq_to_MODEq = [
                0.999988111197046  -0.004472291785614901  -0.0019432114523353138
                0.0044722917853246488  0.99998999924364429  -4.3454795049591017e-06
                0.0019432114530033259  -4.3451807730184788e-06  0.99999811195340182
            ],
            MODEq_to_TODEq = [
                0.99999999676366935  7.3815499794868154e-05  3.199895564956375e-05
                -7.381576564224158e-05  0.99999999724111399  8.306900158072672e-06
                -3.1998342383295368e-05  -8.3092621586677851e-06  0.99999999945353113
            ],
            TODEq_to_PEF = [
                -0.17565628687965903  0.98445155740628032  0
                -0.98445155740628032  -0.17565628687965903  0
                0  0  1
            ],
            PEF_to_ITRF = [
                0.99999999999993106  0  3.7125577258324086e-07
                5.0817622121371807e-13  0.99999999999906319  -1.3688035546968973e-06
                -3.7125577258289305e-07  1.3688035546969918e-06  0.99999999999899425
            ],
            ICRF_to_ITRF_fk5 = [
                -0.17132409315002195  0.98521466666200774  0.0003401476015919656
                -0.98521287432158566  -0.17132443031069583  0.0018793216101906014
                0.0019098108077989341  -1.3144725654938094e-05  0.99999817622328424
            ],
            GCRF_to_CIRS = [
                0.99999817370117816  1.1154584956228619e-08  -0.0019111761583229029
                1.2758522676716011e-08  0.99999999992172195  1.2512234535363388e-05
                0.0019111761583128681  -1.2512236068068551e-05  0.99999817362290011
            ],
            CIRS_to_TIRS = [
                -0.17132448914678355  0.98521465651836182  0
                -0.98521465651836182  -0.17132448914678355  0
                0  0  1
            ],
            TIRS_to_ITRF = [
                0.99999999999993106  -4.5569371753073743e-11  3.7125577258324086e-07
                4.6077547974247913e-11  0.99999999999906319  -1.3688035546968973e-06
                -3.7125577252051754e-07  1.3688035547139095e-06  0.99999999999899425
            ],
            GCRF_to_ITRF_iau2006 = [
                -0.1713241629327448  0.9852146545332815  0.00034012977085301987
                -0.98521286203083869  -0.1713245000603496  0.0018794063091374731
                0.0019098912005315798  -1.3112512280500097e-05  0.99999817607016872
            ],
        ),
    ),
    (
        jd_utc = 2460676.5,
        jd_tdb = 2460676.50080074,
        eop = (dut1_s = 0.046267299999999997, xp_as = 0.144063, yp_as = 0.30510799999999999),
        mean_obliquity = 0.40903606124122099,
        true_obliquity = 0.4090772247346724,
        matrices = (
            ICRF_to_MJ2000Eq = [
                0.99999999999999423  -7.078279744199198e-08  8.0562171469761338e-08
                7.0782794778573375e-08  0.99999999999999689  3.3060414542221364e-08
                -8.0562173809869717e-08  -3.3060408839805517e-08  0.99999999999999623
            ],
            MJ2000Eq_to_MODEq = [
                0.99998141979583943  -0.0055909725392998813  -0.0024292157503235171
                0.0055909725385909943  0.99998437036783339  -6.791194180359036e-06
                0.0024292157519550579  -6.7906105517868323e-06  0.99999704942800605
            ],
            MODEq_to_TODEq = [
                0.99999999999992129  -3.6400401468705461e-07  -1.5779051809696744e-07
                3.6399751916970785e-07  0.99999999915271709  -4.1163493468499013e-05
                1.5780550164015531e-07  4.1163493411044971e-05  0.99999999915277082
            ],
            TODEq_to_PEF = [
                -0.18909170772255351  0.9819594319881898  0
                -0.9819594319881898  -0.18909170772255351  0
                0  0  1
            ],
            PEF_to_ITRF = [
                0.99999999999975608  0  6.9843713341677407e-07
                1.0331319277374167e-12  0.99999999999890599  -1.4792053261587829e-06
                -6.9843713341600994e-07  1.4792053261591437e-06  0.99999999999866207
            ],
            ICRF_to_ITRF_fk5 = [
                -0.18359775521269189  0.98300137014740352  0.00041300022659161408
                -0.98299845785162576  -0.18359821669641449  0.0023930497740945727
                0.0024281973118633355  3.3379980804058793e-05  0.99999705136744843
            ],
            GCRF_to_CIRS = [
                0.99999704850949689  7.6926403441701652e-10  -0.0024296033204269747
                -8.4274931972175282e-08  0.99999999940934858  -3.4369980687082054e-05
                0.0024296033189654866  3.4370083999065019e-05  0.99999704791884747
            ],
            CIRS_to_TIRS = [
                -0.18359828557795355  0.98300135784892806  0
                -0.98300135784892806  -0.18359828557795355  0
                0  0  1
            ],
            TIRS_to_ITRF = [
                0.99999999999975608  -5.6967172159139573e-11  6.9843713341677407e-07
                5.8000304086828562e-11  0.99999999999890599  -1.4792053261587829e-06
                -6.9843713333174382e-07  1.4792053261989316e-06  0.99999999999866207
            ],
            GCRF_to_ITRF_iau2006 = [
                -0.18359782477876124  0.98300135716130599  0.00041298370151531157
                -0.98299844466047837  -0.18359828621932373  0.0023931344316053447
                0.0024282774939722281  3.341193978621993e-05  0.99999705117167947
            ],
        ),
    ),
)

"""
    _truth_angle_μas(A, B) -> Float64

Angle between two rotation matrices, in microarcseconds.

Uses the skew part rather than `acos((tr(R) − 1)/2)`: every angle compared here
is tiny, and near θ = 0 the trace formula evaluates `acos` at `1 − θ²/2`, where
machine epsilon propagates to a relative error of about `eps/θ²`.
"""
function _truth_angle_μas(A::AbstractMatrix, B::AbstractMatrix)
    R = A * transpose(B)
    v = 0.5 .* (R[3,2] - R[2,3], R[1,3] - R[3,1], R[2,1] - R[1,2])
    return rad2deg(asin(clamp(sqrt(sum(abs2, v)), -1.0, 1.0))) * 3600 * 1e6
end

# --- IAU-2006/2000A ----------------------------------------------------------
#
# The shipped default, and the chain held to the reference implementation.
# Every edge measures 0.000–0.005 µas. The bound is ten times that, which still
# catches the Earth-rotation-angle precision loss this comparison found — that
# was 0.703 µas — by a factor of fourteen.

const _TOL_IAU2006 = 0.05

# --- FK5 / IAU-76-80 ---------------------------------------------------------
#
# The legacy chain carries three residuals that are understood and deliberately
# not fixed, because closing them would mean departing from
# SatelliteToolboxTransformations for a chain nobody should be reaching for.
# Each bound sits just above the effect that explains it.

const _TOL_FK5 = (
    # Frame bias and IAU-1976 precession are bit-identical to ERFA.
    ICRF_to_MJ2000Eq  = 0.005,
    MJ2000Eq_to_MODEq = 0.005,
    # STB's `nutation_fk5` carries a 0.4 mas rounding in the mean obliquity
    # (Vallado's 23.439291° against the IERS 84381.448″). Inside the nutation
    # matrix it cancels to first order and leaves δ·Δψ, which peaks near
    # 0.034 µas when Δψ reaches its ~17″ extreme.
    MODEq_to_TODEq    = 0.10,
    # GMST-82 is formed from an intermediate reaching 7.9e8 seconds, so its low
    # bits are spent before the reduction. Bounded by one ulp of that, ~1.8 µas.
    TODEq_to_PEF      = 2.0,
    # The commutator xp·yp: STB orders the two polar-motion rotations the other
    # way from ERFA. A real difference between the approximate polar motion the
    # FK5 convention specifies and ERFA's rigorous form — not a defect. The
    # bound covers polar motion well beyond anything in the IERS record.
    PEF_to_ITRF       = 0.5,
    # The composed chain, dominated by GMST.
    ICRF_to_ITRF_fk5  = 2.5,
)

@testset "Earth chains against ERFA: IAU-2006/2000A" begin
    original = frame_theory()
    try
        set_frame_theory!(IAU2006())
        for case in _TRUTH
            t = Time(case.jd_tdb, 0.0, :tdb, :jd)
            m = case.matrices
            for (truth, from, to) in ((m.GCRF_to_CIRS,         GCRF(), CIRS()),
                                      (m.CIRS_to_TIRS,         CIRS(), TIRS()),
                                      (m.TIRS_to_ITRF,         TIRS(), ITRF()),
                                      (m.GCRF_to_ITRF_iau2006, GCRF(), ITRF()))
                M = Matrix(axes_rotation(from, to, t)[1:3, 1:3])
                @test _truth_angle_μas(M, truth) < _TOL_IAU2006
            end
        end
    finally
        set_frame_theory!(original)
    end
end

@testset "Earth chains against ERFA: FK5 / IAU-76-80" begin
    original = frame_theory()
    try
        set_frame_theory!(FK5())
        for case in _TRUTH
            t = Time(case.jd_tdb, 0.0, :tdb, :jd)
            m = case.matrices
            for (truth, from, to, tol) in
                    ((m.ICRF_to_MJ2000Eq,  ICRF(),     MJ2000Eq(), _TOL_FK5.ICRF_to_MJ2000Eq),
                     (m.MJ2000Eq_to_MODEq, MJ2000Eq(), MODEq(),    _TOL_FK5.MJ2000Eq_to_MODEq),
                     (m.MODEq_to_TODEq,    MODEq(),    TODEq(),    _TOL_FK5.MODEq_to_TODEq),
                     (m.TODEq_to_PEF,      TODEq(),    PEF(),      _TOL_FK5.TODEq_to_PEF),
                     (m.PEF_to_ITRF,       PEF(),      ITRF(),     _TOL_FK5.PEF_to_ITRF),
                     (m.ICRF_to_ITRF_fk5,  ICRF(),     ITRF(),     _TOL_FK5.ICRF_to_ITRF_fk5))
                M = Matrix(axes_rotation(from, to, t)[1:3, 1:3])
                @test _truth_angle_μas(M, truth) < tol
            end
        end
    finally
        set_frame_theory!(original)
    end
end

@testset "Earth chains against ERFA: obliquity" begin
    # The ecliptic edges, where a 0.4 mas rounding lived until this comparison
    # found it. Tight, because there is nothing left to explain a residual.
    original = frame_theory()
    try
        set_frame_theory!(FK5())
        for case in _TRUTH
            t = Time(case.jd_tdb, 0.0, :tdb, :jd)
            for (ε_truth, src, dst) in ((case.mean_obliquity, MODEq(), MODEc()),
                                        (case.true_obliquity, TODEq(), TODEc()))
                R = axes_rotation(src, dst, t)[1:3, 1:3]
                ε_ours = atan(R[2, 3], R[2, 2])       # the X-rotation angle
                @test abs(rad2deg(ε_ours - ε_truth)) * 3600 * 1e6 < 0.01
            end
        end
    finally
        set_frame_theory!(original)
    end
end

@testset "the truth data still describes the EOP it was generated with" begin
    # The comparison is only meaningful while both sides use the same EOP. If
    # the table underneath us moves, the residuals move for reasons that are
    # not code changes — and this is where that shows up, rather than as a
    # mysterious failure in one of the tests above.
    for case in _TRUTH
        jd_utc = case.jd_utc
        @test eop(FK5()).Δut1_utc(jd_utc) ≈ case.eop.dut1_s atol = 1e-9
        @test eop(FK5()).x(jd_utc)        ≈ case.eop.xp_as  atol = 1e-9
        @test eop(FK5()).y(jd_utc)        ≈ case.eop.yp_as  atol = 1e-9
    end
end
